Numpy, sebagai salah satu library yang saling penting di pemrograman yang menggunakan matematika dan angka, memberikan kemudahan dalam melakukan operasi aljabar matriks. Bila deklarasi array ```a = [[1,0],[0,1]]``` memberikan array 2D biasa, maka dengan Numpy, ```a = np.array([[1,0],[0,1]])``` memberikan objek ```a``` yang dapat dilakukan operasi aljabar matriks seperti penjumlahan, pengurangan, perkalian, transpose, dll. 

Pada bab ini, tidak akan dibahas Numpy secara keseluruhan, namun hanya dibahas tentang matriks dan sedikit Aljabar Linear dengan Numpy. 


## Instalasi

Untuk menggunakan Numpy, kita harus melakukan ```import numpy``` karena ia merupakan suatu library yang bukan merupakan standar Python. Apabila Anda menginstall Python dengan Anaconda, kemungkinan besar Numpy sudah terinstal di mesin Anda dan terhubung dengan Python dan Anda bisa **lanjut ke section berikutnya**. Apabila Anda menginstall Python melalui distribusi resmi, kemungkinan Anda belum bisa menggunakan Numpy. Untuk menginstallnya, Anda bisa menggunakan package manager yang Anda gunakan, bisa ```pip``` atau ```conda``` atau yang lainnya. 

Untuk menginstall dengan pip, cukup buka terminal (Windows: commandprompt) dan mengetikkan perintah berikut.

Apabila Anda menggunakan miniconda atau anaconda, Anda bisa menginstall dengan perintah berikut. 

Apabila Anda kebetulan menggunakan Ubuntu 20.04 LTS, Anda bisa menginstall lewat aptitude. 

## Dasar-dasar

Untuk menggunakan Numpy kita perlu mengimportnya. Biasanya import dilakukan dengan memberi singkatan np seperti di bawah ini. 

In [2]:
import numpy as np

Kalau yang dibutuhkan hanya salah satu modul dari numpy dan tidak semuanya, import bisa dilakukan dengan perintah ```from ... import ...``` sebagai berikut. 

In [ ]:
from scipy import some_module
some_module.some_function()

### Array

Array pada Numpy berbeda dengan array pada module bawaan Python. Pada module bawaan Python, ```array.array```  hanya memiliki fungsi terbatas. Pada Numpy, array disebut ```ndarray``` (dulu) atau ```array``` (alias).  
Kita bisa membuat array dengan ```np.array()```. Beberapa matriks khusus juga bisa langsung dibuat. 

In [58]:
import numpy as np

a = np.array([[1,2,1],[1,0,1]])
b = np.arange(7)
c = np.arange(3,10)
print("a = ")
print(a)
print("b = ")
print(b)
print(c)
print()
# Special matrix

I = np.ones(3)
O = np.zeros(4)
I2 = np.ones((2,4))
O2 = np.zeros((3,3))

print("spesial matrix")
print("satu =",I)
print("nol = ",O)
print("matriks isi 1, dua dimensi")
print(I2)
print("nol dua dimensi =")
print(O2)

a = 
[[1 2 1]
 [1 0 1]]
b = 
[0 1 2 3 4 5 6]
[3 4 5 6 7 8 9]

spesial matrix
satu = [1. 1. 1.]
nol =  [0. 0. 0. 0.]
matriks isi 1, dua dimensi
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
nol dua dimensi =
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Beberapa kesalahan dalam membuat array seringkali terjadi karena kesalahan pada kurung. Ingat bahwa array ini adalah suatu fungsi, sehingga membutuhkan kurung biasa atau parenthesis sedangkan array membutuhkan kurung siku atau brackets. Pada prakteknya, ketika dimensi array lebih dari satu, setelah mengambil brackets di paling luar, menggunakan parenthesis lagi di dalam. 

In [45]:
# Salah
x = np.array(1,2,3)  

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [46]:
# Benar
x = np.array([1,2,3])

In [48]:
y = np.array([[1,0,0],[0,1,0]])
z = np.array([(1,0,0),(0,1,0)])

y-z

array([[0, 0, 0],
       [0, 0, 0]])

### Vektor

Secara matematis, vektor merupakan bentuk khusus dari matriks. Namun, di Numpy vektor bisa dideklarasikan dengan cara yang berbeda. Dua cara yang cukup sering digunakan adalah dengan ```arange``` dan dengan ```linspace```. Perbedaan keduanya ada pendeklarasiannya. Bila ```arange``` mengambil input start, stop, dan step, maka ```linspace``` ini mengambil input start, stop, dan banyaknya entri. Ide dari ```linspace``` ini adalah membuat satu vektor yang jarak antar entrinya sama. 


In [79]:
# deklarasi biasa dengan menuliskan inputnya satu demi satu
vektor = np.array([1,5])
print(vektor)


# deklarasi dengan arange: start, stop, step
vektor1 = np.arange(start=1, stop=10, step=1)
vektor2 = np.arange(0,9,1)

print(vektor1, vektor2)

# deklarasi dengan linspace: start, stop, banyak titik
vektor3 = np.linspace(1,10,4)

print(vektor3)

[1 5]
[1 2 3 4 5 6 7 8 9] [0 1 2 3 4 5 6 7 8]
[ 1.  4.  7. 10.]


## Manipulasi Bentuk


Sebelum memanipulasi bentuk, kita bisa mengecek 'ukuran' dari matriks dengan ```np.shape```; panjang dengan ```np.dim``` dan banyaknya entri dengan ```np.size```. 

In [ ]:
np.shape(a)

In [ ]:
np.ndim(a)

In [ ]:
np.size(a)

Karena shape, dim, size dan lain-lain merupakan fungsi di numpy, bisa juga dipanggil dengan menambahkan fungsinya di belakang objek seperti contoh berikut.

In [ ]:
a.shape

In [ ]:
a.ndim

In [ ]:
a.size

Berikutnya, untuk mengubah bentuk matriks (reshape) kita bisa menyusun ulang matriks dengan perintah ```np.reshape```. Seperti halnya ```shape```, ```ndim```, dan ```size```, kita bisa memanggil ```reshape``` di depan sebagai fungsi dan di belakang sebagai atribut. Matriks juga punya 

In [62]:
b = np.reshape(y,(1,6))   # reshape menjadi ukuran (1,6)
c = z.reshape(6,1)        # reshape menjadi ukuran (6,1)
d = c.T                   # return berupa transpose dari matriks 
e = np.transpose(d)

print(b)
print(c)

b.shape, c.shape, d.shape, e.shape

[[1 0 0 0 1 0]]
[[1]
 [0]
 [0]
 [0]
 [1]
 [0]]


((1, 6), (6, 1), (1, 6), (6, 1))

Bila reshape dan transpose ini bersifat non-destruktif (tidak mengubah objek aslinya), maka untuk mengubah bentuk matriks dengan mengubah objeknya bisa dilakukan dengan resize. 

In [68]:
print(a)
a.reshape((1,6))
print("setelah reshape")
print(a)

[[1 2 1]
 [1 0 1]]
setelah reshape
[[1 2 1]
 [1 0 1]]


In [69]:
print(a)
a.resize((1,6))
print("setelah resize")
print(a)

[[1 2 1]
 [1 0 1]]
setelah resize
[[1 2 1 1 0 1]]


### Melakukan Iterasi dengan Matrix


Pada matriks, kita bisa melakukan iterasi berdasarkan elemen-elemen matriks. Misalkan axis pertama (_row_) atau bahkan seluruh elemennya. 

In [5]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
for row in a:
    print("baris:",row)

baris: [1 2 3]
baris: [4 5 6]
baris: [7 8 9]
baris: [10 11 12]


In [11]:
for elemen in a.flat:
    print(elemen)

1
2
3
4
5
6
7
8
9
10
11
12


### Indexing dan Slicing

Mengambil satu elemen dari matrix mirip dengan mengambil dari sequence: kita cuma perlu tahu koordinatnya. Apabila matriks satu dimensi, maka koordinat cuma perlu satu dimensi. Apabila matriks 2D, maka koordinatnya perlu dua input, dst. Sementara itu, mengambil beberapa elemen dari satu array sering disebut dengan _slicing_ (memotong). 

In [22]:
# Indexing 
A_1D = np.array([0,1,1,2,3,5,8,13,21])
B_2D = np.array([A_1D,A_1D+2])
C_3D = np.array([B_2D,B_2D*2,B_2D*3,B_2D*4])

In [23]:
C_3D

array([[[ 0,  1,  1,  2,  3,  5,  8, 13, 21],
        [ 2,  3,  3,  4,  5,  7, 10, 15, 23]],

       [[ 0,  2,  2,  4,  6, 10, 16, 26, 42],
        [ 4,  6,  6,  8, 10, 14, 20, 30, 46]],

       [[ 0,  3,  3,  6,  9, 15, 24, 39, 63],
        [ 6,  9,  9, 12, 15, 21, 30, 45, 69]],

       [[ 0,  4,  4,  8, 12, 20, 32, 52, 84],
        [ 8, 12, 12, 16, 20, 28, 40, 60, 92]]])

In [24]:
print(A_1D[4],B_2D[0,0],C_3D[0,0,0])

3 0 0


In [25]:
# Contoh slicing
B_2D

array([[ 0,  1,  1,  2,  3,  5,  8, 13, 21],
       [ 2,  3,  3,  4,  5,  7, 10, 15, 23]])

In [26]:
# slicing bisa diambil dengan satu koordinat
B_2D[1]

array([ 2,  3,  3,  4,  5,  7, 10, 15, 23])

In [27]:
B_2D[1,:]

array([ 2,  3,  3,  4,  5,  7, 10, 15, 23])

In [28]:
B_2D[:,1]

array([1, 3])

In [29]:
# slicing pada matriks 3D
C_3D

array([[[ 0,  1,  1,  2,  3,  5,  8, 13, 21],
        [ 2,  3,  3,  4,  5,  7, 10, 15, 23]],

       [[ 0,  2,  2,  4,  6, 10, 16, 26, 42],
        [ 4,  6,  6,  8, 10, 14, 20, 30, 46]],

       [[ 0,  3,  3,  6,  9, 15, 24, 39, 63],
        [ 6,  9,  9, 12, 15, 21, 30, 45, 69]],

       [[ 0,  4,  4,  8, 12, 20, 32, 52, 84],
        [ 8, 12, 12, 16, 20, 28, 40, 60, 92]]])

In [30]:
C_3D[1]

array([[ 0,  2,  2,  4,  6, 10, 16, 26, 42],
       [ 4,  6,  6,  8, 10, 14, 20, 30, 46]])

In [32]:
C_3D[1,:,:]

array([[ 0,  2,  2,  4,  6, 10, 16, 26, 42],
       [ 4,  6,  6,  8, 10, 14, 20, 30, 46]])

In [33]:
C_3D[:,1,:]

array([[ 2,  3,  3,  4,  5,  7, 10, 15, 23],
       [ 4,  6,  6,  8, 10, 14, 20, 30, 46],
       [ 6,  9,  9, 12, 15, 21, 30, 45, 69],
       [ 8, 12, 12, 16, 20, 28, 40, 60, 92]])

In [34]:
C_3D[:,:,1]

array([[ 1,  3],
       [ 2,  6],
       [ 3,  9],
       [ 4, 12]])

In [47]:
# slicing lebih dari satu kolom/baris

A = np.linspace(0,9,10)
B, C = A + 10, A + 20

X = np.array([A,B,C])

In [48]:
X

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.]])

In [53]:
X[0:2,3], X[0:3,3], X[1:3,3]

(array([ 3., 13.]), array([ 3., 13., 23.]), array([13., 23.]))

In [56]:
X[1:3,1:5]

array([[11., 12., 13., 14.],
       [21., 22., 23., 24.]])

## Operasi Matriks

### Operasi Dasar

Pada operasi matriks dengan menggunakan numpy, satu hal yang perlu diperhatikan adalah ada dua jenis operasi, yaitu operasi *element-wise* dan operasi matriks. Operasi *element-wise* menggunakan tanda operasi seperti halnya pada data berbentuk ```integer``` atau ```float```. Operasi perkalian matriks menggunakan tanda ```@``` untuk versi Python yang lebih tinggi dari 3.5; untuk versi sebelumnya harus menggunakan fungsi ```np.matmul``` dengan dua input. 

In [2]:
A = np.array([1,2,3,4,5,6])
B = np.array([[1,1,1],[1,0,1],[0,1,1]])
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.array([[1,1],[1,0]])

In [3]:
2*A

array([ 2,  4,  6,  8, 10, 12])

In [4]:
A+3*A + 3*A**2+A**3

array([  8,  28,  66, 128, 220, 348])

In [48]:
A**2

array([ 1,  4,  9, 16, 25, 36])

In [49]:
C**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [5]:
A < 5

array([ True,  True,  True,  True, False, False])

In [7]:
np.sin(A)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ])

### Perkalian Matriks 

In [35]:
B @ C

array([[12, 15, 18],
       [ 8, 10, 12],
       [11, 13, 15]])

In [37]:
d

In [39]:
B @ D

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [40]:
print(B.shape,D.shape)

(3, 3) (2, 2)


### Perkalian Matriks dengan 'vektor'

In [33]:
x1 = np.ones(3)
x2 = np.ones((3,1))
x3 = np.ones((1,3))

In [31]:
# Perkalian Matriks 3x3 dengan vektor 3x1
B @ x1

array([3., 2., 2.])

In [32]:
B @ x2

array([[3.],
       [2.],
       [2.]])

In [41]:
B @ x3

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

## Beberapa Contoh